/**
 * An error generated by fetch.
 */
export default class FetchError extends Error {
  name: string = 'FetchError'
  response: Response

  /**
   * Creat a fetch error.
   * @param {Response} response - The fetch response.
   * @param  {...any} params - Any other Error params.
   */
  constructor(response: Response, ...params: any[]) {
    super(...params)

    if (Error.captureStackTrace) {
      Error.captureStackTrace(this, FetchError)
    }

    this.response = response
  }
}
